### ISSUE TITLE
:first-day-of-week broken on clojurescript

### ISSUE THREAD

**Issue by livtanong** [gfZeng/time.clj#11]
```
Error: No protocol method IDate.time-zone-offset defined for type cljs.core/Keyword: :first-day-of-week
    at Object.cljs$core$missing_protocol [as missing_protocol] (http://localhost:8080/js/cljs-runtime/cljs.core.js:309:9)
    at Object.time$core$time_zone_offset [as time_zone_offset] (http://localhost:8080/js/cljs-runtime/time.core.js:350:17)
    at Function.cljs$core$IFn$_invoke$arity$variadic (http://localhost:8080/js/cljs-runtime/time.core.js:563:91)
    at time$core$date (http://localhost:8080/js/cljs-runtime/time.core.js:549:23)
    at eval (eval at <anonymous> (http://localhost:8080/js/cljs-runtime/shadow.cljs.devtools.client.browser.js:823:8), <anonymous>:1:16)
    at http://localhost:8080/js/cljs-runtime/shadow.cljs.devtools.client.browser.js:823:8
    at Object.shadow$cljs$devtools$client$env$repl_call [as repl_call] (http://localhost:8080/js/cljs-runtime/shadow.cljs.devtools.client.env.js:141:108)
    at Object.shadow$cljs$devtools$client$browser$repl_invoke [as repl_invoke] (http://localhost:8080/js/cljs-runtime/shadow.cljs.devtools.client.browser.js:821:46)
    at shadow$cljs$devtools$client$browser$handle_message (http://localhost:8080/js/cljs-runtime/shadow.cljs.devtools.client.browser.js:901:44)
    at Object.shadow$cljs$devtools$client$env$process_ws_msg [as process_ws_msg] (http://localhost:8080/js/cljs-runtime/shadow.cljs.devtools.client.env.js:261:102)
```

Repro:
```clj
(require '[time.core :as t])
(t/date :first-day-of-week 1)
(t/date :first-day-of-week :monday)
;; Both result in the stack trace above.
```

Works perfectly fine in Clojure.

**Comment by spagreeks** [comment]
Usage: `(t/date (t/now-ms) :frist-day-of-week :monday)`
